'''
This will be a set of code that I am making because I'm bored I guess...
Basically what this Bull Sh*t is going to do is give the user the ability to
read in radar file pictures generated by RadCAT along with HVPS-3 images from 
SODA processing code, and display these images along with other microphysics 
information. This code will also be interactive so that you can select the time 
that you are interested in and can advance throughout the times avaliable to you
in the Citation II aircraft microphysics file. The eventual future plan will
also allow for customization of what is all displayed on the GUI. 

Appended below is the old code that worked in jupyter lab.

'''
import tkinter as tk 
from tkinter import filedialog
import xarray as xr
import os
import numpy as np
from matplotlib.gridspec import GridSpec
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

# Initialization of the RadCAT display GUI
root = tk.Tk()
root.title("RadCAT Display GUI")
root.geometry("1000x600")
root.configure(bg='white')

# Code to return a radar file directory
def select_directory_radar():
    global radar_dir
    radar_dir = filedialog.askdirectory(title='Select a folder') + '/'

    if radar_dir:
        radar_path_label.config(text=radar_dir)

radar_file_button = tk.Button(root, text = 'Browse Folder', command = select_directory_radar)
radar_file_button.place(x = 10, y = 0)
radar_label = tk.Label(root, text = 'Radar directory selected', font = ('Arial', 10))
radar_label.place(x = 100, y = 0)
radar_path_label = tk.Label(root, text = 'No file selected')
radar_path_label.place(x=275, y = 0)

# Code to return a hvps-3 file directory
def select_directory_hvps():
    global hvps_dir
    hvps_dir = filedialog.askdirectory(title='Select a folder') + '/'

    if hvps_dir:
        hvps_path_label.config(text=hvps_dir)

hvps_file_button = tk.Button(root, text = 'Browse Folder', command = select_directory_hvps)
hvps_file_button.place(x = 10, y = 30)
hvps_label = tk.Label(root, text = 'HVPS-3 directory selected', font = ('Arial', 10))
hvps_label.place(x = 100, y = 30)
hvps_path_label = tk.Label(root, text = 'No file selected')
hvps_path_label.place(x=275, y = 30)

# Code to return a microphysics file 
def select_directory_micro():
    global micro_file
    micro_file = filedialog.askopenfilenames(title='Select a file')

    if micro_file:
        micro_path_label.config(text=micro_file)

micro_file_button = tk.Button(root, text = 'Browse Folder', command = select_directory_micro)
micro_file_button.place(x = 10, y = 60)
micro_label = tk.Label(root, text = 'Mirophysics file selected', font = ('Arial', 10))
micro_label.place(x = 100, y = 60)
micro_path_label = tk.Label(root, text = 'No file selected')
micro_path_label.place(x=275, y = 60)

# This section will update what is being displayed given the x axis input from the selectable graph
time_selected = 100
def xaxis_click(event):
    if event.xdata is not None:
        global time_selected 
        time_selected = round(event.xdata, 2)

# This section loads in the data directories and files that were selected to then display them 
def load_data_but():

    # Define figure and axis that the data will be plotted on 
    fig = Figure(figsize =(8, 6))
    
    gs = GridSpec(4, 15, figure=fig)
    ax1 = fig.add_subplot(gs[0:3, 0:10])
    ax2 = fig.add_subplot(gs[0:, -4:])
    ax3 = fig.add_subplot(gs[3:, 0:4])
    ax4 = fig.add_subplot(gs[3:, 6:10])

    try:
        # load in cloud microphysics data file
        global micro_file
        micro_file = micro_file[0]
        global cloud_micro
        cloud_micro = xr.open_dataset(micro_file, engine='netcdf4')

        # Interactive graph that allows the user to select the area of flight that they are interested in 
        
        # Altitude plot
        cloud_micro.POS_Alt.plot(ax = ax3, color = 'black')
        ##ax3.axvline(x=cloud_micro.Time.data[time], color='black', linestyle = '--', linewidth = .5)

        # Altitude plot marker selected
        ax3.plot(cloud_micro.Time.data[time_selected], cloud_micro.POS_Alt.data[time_selected], color = 'black', marker = 'o', markersize = 5)

        # Temperature plot
        ax5 = ax3.twinx()
        cloud_micro.Air_Temp.plot(ax = ax5)

        # Temperature plot marker selected 
        ax5.plot(cloud_micro.Time.data[time_selected], cloud_micro.Air_Temp.data[time_selected], color = 'blue', marker = 'o', markersize = 5)
        ax5.set_ylabel('Air Temperature (C)')
        
        ax3.set_title('Aircraft Altitude/Temperature Time Series', fontsize = 10)
        ax3.set_xlabel('Time (sfm)')
        ax3.set_ylabel('Altitude (m)')
        canvas = FigureCanvasTkAgg(fig, master = root)
        canvas.get_tk_widget().place(x = 10, y = 120)

        fig.canvas.mpl_connect('button_press_event', xaxis_click)

    except:
        micro_path_label.config(text='File not found')

    try:
        # Read through directory with HVPS images
        global hvps_dir
        hvps_files = os.listdir(hvps_dir)

    except:
        hvps_path_label.config(text='Directory not found')

    try:
        # Read through directory with Aircraft PPI images 
        global radar_dir
        radar_files = os.listdir(os.path.dirname(radar_dir))

    except:
        radar_path_label.config(text='Directory not found')

load_data_button = tk.Button(
    root, 
    text='Load Data',
    command=load_data_but,
    bg='blue',
    fg='white'
)
load_data_button.place(x = 10, y = 90)

# Phase classifications list
precip_classes = ['Drizzel', 'Rain', 'Ice Crystals', 'Aggregates', 'Wet Snow', 'Vertical Ice', 'Low-Density Graupel', 'High-Density Graupel', 'Hail', 'Big Drops']


'''
# Plotting function 
def plotting_func():
        # Defines what data products should be plotted 
        radar_file_plot = radar_files[counter]
        hvps_image = plt.imread(f'flight_data/HVPS3_Images/{hvps_files[np.argmin(abs(hvps_files_list - radar_file_list[counter]))].name}')
        matrix = np.asarray(hvps_image)
        
        # Finds the appropriate time index for aircraft data to be plotted 
        time = np.argmin(abs(np.array(cloud_micro.Time.data) - radar_file_list[counter]))

        # Clear any output that may be displayed before plotting new display
        clear_output(wait=True)
        
        # Define figure and axis that the data will be plotted on 
        fig = plt.figure(figsize =(12, 8))
        
        gs = GridSpec(4, 15, figure=fig)
        ax1 = fig.add_subplot(gs[0:3, 0:10])
        ax2 = fig.add_subplot(gs[0:, -4:])
        ax3 = fig.add_subplot(gs[3:, 0:4])
        ax4 = fig.add_subplot(gs[3:, 6:10])
        
        # Plot radar PPI with aircraft overlay
        image_radar = plt.imread(f'radar_images2/{radar_file_plot.name}')
        ax1.imshow(image_radar)
        ax1.set_xticks([])
        ax1.set_yticks([])
        ax1.set_title('C-SAPR Ground Radar PPI Scan at Aircraft Altitude', fontsize = 10)

        # Phase classification label 
        ax1.text(0.5, 0.02, f'BEST GUESS PRECIP TYPE: {precip_classes[int(cloud_micro.Phase_Classification[time].data)]}', 
                color = 'red',
                fontsize = 10,
                horizontalalignment='center', 
                verticalalignment='bottom', 
                transform=ax1.transAxes)

        # HVPS-3 Particle image display
        ax2.imshow(hvps_image)
        ax2.set_xticks([])
        ax2.set_yticks([])
        ax2.set_title('HVPS-3 Particle Images', fontsize = 10)
        ax2.set_xlabel(f'{hvps_files[np.argmin(abs(hvps_files_list - radar_file_list[counter]))].name}')
        
        # Altitude/Temperature time series plot
        try:
            cloud_micro.POS_Alt[0:time].plot(ax = ax3, color = 'black')
            ax3.axvline(x=cloud_micro.Time.data[time], color='black', linestyle = '--', linewidth = .5)

            # Altitude plot
            ax3.plot([cloud_micro.Time.data[0], cloud_micro.Time.data[time]], [cloud_micro.POS_Alt.data[time], cloud_micro.POS_Alt.data[time]], color = 'black', linestyle = '--', linewidth = .5)
            ax3.plot(cloud_micro.Time.data[time], cloud_micro.POS_Alt.data[time], color = 'black', marker = 'o', markersize = 5)

            # Temperature plot
            ax5 = ax3.twinx()
            cloud_micro.Air_Temp[0:time].plot(ax = ax5)
            ax5.plot(cloud_micro.Time.data[time], cloud_micro.Air_Temp.data[time], color = 'blue', marker = 'o', markersize = 5)
            ax5.set_ylabel('Air Temperature (C)')
            
            ax3.set_title('Aircraft Altitude/Temperature Time Series', fontsize = 10)
            ax3.set_xlim([cloud_micro.Time.data[0], cloud_micro.Time.data[time] + 100])
            ax3.set_xlabel('Time (sfm)')
            ax3.set_ylabel('Altitude (m)')
            
        except:
            ax3.set_title('Aircraft Altitude Time Series', fontsize = 10)
            ax3.text(.5, .5, 'No Available Data')

        # HVPS particle size distribution plot
        try:
            hvps_data = [cloud_micro.HVPS_Ch1.data[time], cloud_micro.HVPS_Ch2.data[time], cloud_micro.HVPS_Ch3.data[time], cloud_micro.HVPS_Ch4.data[time], 
                         cloud_micro.HVPS_Ch5.data[time], cloud_micro.HVPS_Ch6.data[time], cloud_micro.HVPS_Ch7.data[time], cloud_micro.HVPS_Ch8.data[time],
                         cloud_micro.HVPS_Ch9.data[time], cloud_micro.HVPS_Ch10.data[time], cloud_micro.HVPS_Ch11.data[time], cloud_micro.HVPS_Ch12.data[time],
                         cloud_micro.HVPS_Ch13.data[time], cloud_micro.HVPS_Ch14.data[time], cloud_micro.HVPS_Ch15.data[time], cloud_micro.HVPS_Ch16.data[time],
                         cloud_micro.HVPS_Ch17.data[time], cloud_micro.HVPS_Ch18.data[time], cloud_micro.HVPS_Ch19.data[time], cloud_micro.HVPS_Ch20.data[time],
                         cloud_micro.HVPS_Ch21.data[time], cloud_micro.HVPS_Ch22.data[time], cloud_micro.HVPS_Ch23.data[time], cloud_micro.HVPS_Ch24.data[time],
                         cloud_micro.HVPS_Ch25.data[time], cloud_micro.HVPS_Ch26.data[time], cloud_micro.HVPS_Ch27.data[time], cloud_micro.HVPS_Ch28.data[time]]  
            
            # Bin name descriptions
            hvps_desc = ['300 um', '500 um', '700 um', '900 um',
                         '1100 um', '1300 um', '1500 um', '1700 um',
                         '2000 um', '2400 um', '2800 um', '3200 um',
                         '3600 um', '4000 um', '4400 um', '4800 um', 
                         '5500 um', '6500 um', '7500 um', '8500 um', 
                         '9500 um', '11000 um', '13000 um', '15000 um', 
                         '17000 um', '19000 um', '22500 um', '27500 um']
            
            # Plotting of HVPS PSD data 
            ax4.bar(hvps_desc, hvps_data)
            ax4.tick_params(axis='x', labelrotation=-90)
            ax4.set_ylabel('Concentration (#/cm^3)')
            ax4.set_xlabel('Bin size (um)')
            ax4.tick_params(axis='both', labelsize=5)
            ax4.set_title('HVPS-3 Particle Size Distribution', fontsize = 10)

        except:
            ax4.set_title('HVPS-3 Particle Size Distribution', fontsize = 10)
            


# Function for forward button click
def forward_button_click(b):
    with output:
        # Counter logic
        global counter 
        counter += 1
        if counter == len(radar_file_list):
            counter = 0

        plotting_func(counter)

        
# Function for backward button click 
def backward_button_click(b):
    with output:
        # Counter logic
        global counter 
        counter -= 1
        if counter < 0:
            counter = len(radar_file_list) - 1

        plotting_func(counter)

canvas = FigureCanvasTkAgg(fig, master=root)
canvas.draw()
canvas.get_tk_widget().pack(side=tk.TOP, fill=tk.BOTH, expand=True)  
'''

root.mainloop()